### ISSUE TITLE
+ PageController

### ISSUE THREAD

**Issue by Bunkermaster** [Ikimasoft/CMSG2#5]
Création du controller de Page qui va contenir les méthodes suivantes:
- ajoutAction
- supprimerAction
- modifierAction
- detailsAction
- listeAction
- displayAction

**Comment by Ikimasoft** [comment]
Pour créer les méthodes à partir de la liste:
copier la liste des méthodes et la coller dans le corps du controller
command+r | control+r (search and replace)
sélectionner les noms de méthodes et:
* rechercher : ^(.*)$
* remplacer :    public function $1()\n   {\n   }\n
